 
****************************************
Report : resources
Design : SNN
Version: T-2022.03
Date   : Mon Apr 24 00:39:20 2023
****************************************


Resource Report for this hierarchy in file
        /RAID2/COURSE/iclab/iclab034/Lab08/EXERCISE/01_RTL/SNN.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gt_x_1         | DW_cmp         | width=6    | gt_168 (SNN.v:168)         |
| lt_x_2         | DW_cmp         | width=6    | lt_168 (SNN.v:168)         |
| lt_x_36        | DW_cmp         | width=6    | lt_329 (SNN.v:329)         |
| gt_x_37        | DW_cmp         | width=6    | gt_330 (SNN.v:330)         |
| lt_x_38        | DW_cmp         | width=6    | lt_330 (SNN.v:330)         |
| gt_x_39        | DW_cmp         | width=6    | gt_331 (SNN.v:331)         |
| lt_x_40        | DW_cmp         | width=6    | lt_331 (SNN.v:331)         |
| gt_x_41        | DW_cmp         | width=6    | gt_332 (SNN.v:332)         |
| div_77         | DW_div_uns     | a_width=20 | div_513 (SNN.v:513)        |
|                |                | b_width=12 |                            |
| div_78         | DW_div_uns     | a_width=17 | div_514 (SNN.v:514)        |
|                |                | b_width=9  |                            |
| gt_x_79        | DW_cmp         | width=8    | gt_519 (SNN.v:519)         |
| gt_x_81        | DW_cmp         | width=8    | gt_520 (SNN.v:520)         |
| gt_x_83        | DW_cmp         | width=8    | gt_521 (SNN.v:521)         |
| gt_x_85        | DW_cmp         | width=8    | gt_523 (SNN.v:523)         |
| gt_x_87        | DW_cmp         | width=8    | gt_524 (SNN.v:524)         |
| gt_x_89        | DW_cmp         | width=8    | gt_525 (SNN.v:525)         |
| sub_x_99       | DW01_sub       | width=9    | sub_542 (SNN.v:542)        |
| sub_x_100      | DW01_sub       | width=9    | sub_543 (SNN.v:543)        |
| sub_x_101      | DW01_sub       | width=9    | sub_544 (SNN.v:544)        |
| sub_x_102      | DW01_sub       | width=9    | sub_545 (SNN.v:545)        |
| sub_x_103      | DW01_sub       | width=8    | sub_547 (SNN.v:547)        |
| sub_x_104      | DW01_sub       | width=8    | sub_548 (SNN.v:548)        |
| sub_x_105      | DW01_sub       | width=8    | sub_549 (SNN.v:549)        |
| sub_x_106      | DW01_sub       | width=8    | sub_550 (SNN.v:550)        |
| gt_x_113       | DW_cmp         | width=6    | gt_163 (SNN.v:163)         |
|                |                |            | gt_329 (SNN.v:329)         |
|                |                |            | gt_445 (SNN.v:445)         |
|                |                |            | gt_446 (SNN.v:446)         |
|                |                |            | gt_447 (SNN.v:447)         |
|                |                |            | gt_448 (SNN.v:448)         |
|                |                |            | gt_450 (SNN.v:450)         |
|                |                |            | gt_451 (SNN.v:451)         |
|                |                |            | gt_452 (SNN.v:452)         |
|                |                |            | gt_453 (SNN.v:453)         |
|                |                |            | gt_454 (SNN.v:454)         |
|                |                |            | gt_455 (SNN.v:455)         |
|                |                |            | gt_456 (SNN.v:456)         |
|                |                |            | gt_457 (SNN.v:457)         |
|                |                |            | gt_458 (SNN.v:458)         |
|                |                |            | gt_459 (SNN.v:459)         |
|                |                |            | gt_460 (SNN.v:460)         |
|                |                |            | gt_461 (SNN.v:461)         |
|                |                |            | gt_462 (SNN.v:462)         |
|                |                |            | gt_463 (SNN.v:463)         |
| gt_x_114       | DW_cmp         | width=6    | gt_167 (SNN.v:167)         |
|                |                |            | gt_169 (SNN.v:169)         |
| lt_x_115       | DW_cmp         | width=6    | lt_167 (SNN.v:167)         |
|                |                |            | lt_169 (SNN.v:169)         |
| lt_x_116       | DW_cmp         | width=6    | lt_309_G3_G3 (SNN.v:309)   |
|                |                |            | lt_316 (SNN.v:316)         |
|                |                |            | lt_316_G2 (SNN.v:316)      |
|                |                |            | lt_316_G2_G1 (SNN.v:316)   |
|                |                |            | lt_316_G2_G2 (SNN.v:316)   |
|                |                |            | lt_316_G2_G3 (SNN.v:316)   |
|                |                |            | lt_316_G3 (SNN.v:316)      |
|                |                |            | lt_316_G3_G1 (SNN.v:316)   |
|                |                |            | lt_316_G3_G2 (SNN.v:316)   |
| gt_x_117       | DW_cmp         | width=3    | gt_442 (SNN.v:442)         |
|                |                |            | gt_531 (SNN.v:531)         |
|                |                |            | gt_532 (SNN.v:532)         |
|                |                |            | gt_533 (SNN.v:533)         |
|                |                |            | gt_534 (SNN.v:534)         |
|                |                |            | gt_535 (SNN.v:535)         |
|                |                |            | gt_536 (SNN.v:536)         |
|                |                |            | gt_537 (SNN.v:537)         |
|                |                |            | gt_538 (SNN.v:538)         |
| lt_x_118       | DW_cmp         | width=6    | lt_497 (SNN.v:497)         |
|                |                |            | lt_498 (SNN.v:498)         |
| gt_x_119       | DW_cmp         | width=6    | gt_497 (SNN.v:497)         |
|                |                |            | gt_498 (SNN.v:498)         |
| add_x_6        | DW01_inc       | width=6    | add_246 (SNN.v:246)        |
|                |                |            | add_247 (SNN.v:247)        |
| DP_OP_293J1_122_2512            |            |                            |
|                | DP_OP_293J1_122_2512 |      |                            |
| DP_OP_294J1_123_9307            |            |                            |
|                | DP_OP_294J1_123_9307 |      |                            |
| DP_OP_295J1_124_2519            |            |                            |
|                | DP_OP_295J1_124_2519 |      |                            |
=============================================================================

Datapath Report for DP_OP_293J1_122_2512
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_293J1_122_2512 | add_561 (SNN.v:561) add_561_2 (SNN.v:561)           |
|                      | add_561_3 (SNN.v:561)                               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 + I4 (SNN.v:561)            |
==============================================================================

Datapath Report for DP_OP_294J1_123_9307
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_294J1_123_9307 | mult_470 (SNN.v:470) add_490 (SNN.v:490)            |
|                      | mult_470_G2 (SNN.v:470) add_491 (SNN.v:491)         |
|                      | add_494 (SNN.v:494) add_492 (SNN.v:492)             |
|                      | add_494_2 (SNN.v:494) add_493 (SNN.v:493)           |
|                      | add_494_3 (SNN.v:494) add_494_4 (SNN.v:494)         |
|                      | mult_470_G3 (SNN.v:470) mult_470_G4 (SNN.v:470)     |
|                      | mult_470_G5 (SNN.v:470) mult_470_G6 (SNN.v:470)     |
|                      | mult_470_G7 (SNN.v:470) mult_470_G8 (SNN.v:470)     |
|                      | mult_470_G9 (SNN.v:470)                             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| I5    | PI   | Unsigned | 8     |                                          |
| I6    | PI   | Unsigned | 8     |                                          |
| I7    | PI   | Unsigned | 8     |                                          |
| I8    | PI   | Unsigned | 8     |                                          |
| I9    | PI   | Unsigned | 8     |                                          |
| I10   | PI   | Unsigned | 8     |                                          |
| I11   | PI   | Unsigned | 8     |                                          |
| I12   | PI   | Unsigned | 8     |                                          |
| I13   | PI   | Unsigned | 8     |                                          |
| I14   | PI   | Unsigned | 8     |                                          |
| I15   | PI   | Unsigned | 8     |                                          |
| I16   | PI   | Unsigned | 8     |                                          |
| I17   | PI   | Unsigned | 8     |                                          |
| I18   | PI   | Unsigned | 8     |                                          |
| T108  | IFO  | Unsigned | 16    | I5 * I6 (SNN.v:470)                      |
| T109  | IFO  | Unsigned | 16    | I7 * I8 (SNN.v:470)                      |
| T106  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:470)                      |
| T107  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:470)                      |
| T110  | IFO  | Unsigned | 16    | I9 * I10 (SNN.v:470)                     |
| T111  | IFO  | Unsigned | 16    | I11 * I12 (SNN.v:470)                    |
| T112  | IFO  | Unsigned | 16    | I13 * I14 (SNN.v:470)                    |
| T113  | IFO  | Unsigned | 16    | I15 * I16 (SNN.v:470)                    |
| T114  | IFO  | Unsigned | 16    | I17 * I18 (SNN.v:470)                    |
| O1    | PO   | Unsigned | 17    | T106 + T107 (SNN.v:490)                  |
| O2    | PO   | Unsigned | 20    | T108 + T109 + O1 + T110 + T111 + T112 + T113 + T114 ( SNN.v:491 SNN.v:492 SNN.v:493 SNN.v:494 ) |
==============================================================================

Datapath Report for DP_OP_295J1_124_2519
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_295J1_124_2519 | mult_506 (SNN.v:506) add_506 (SNN.v:506)            |
|                      | mult_506_2 (SNN.v:506)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| T131  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:506)                      |
| T132  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:506)                      |
| O1    | PO   | Unsigned | 17    | T131 + T132 (SNN.v:506)                  |
==============================================================================


Resource Report for Ungrouped Hierarchy div_78
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy div_77
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'sub_547 (SNN.v:547)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3106 (SNN.v:556)'.  (HDL-120)

Information: Operator associated with resources 'sub_548 (SNN.v:548)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3107 (SNN.v:557)'.  (HDL-120)

Information: Operator associated with resources 'sub_549 (SNN.v:549)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3108 (SNN.v:558)'.  (HDL-120)

Information: Operator associated with resources 'sub_550 (SNN.v:550)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3109 (SNN.v:559)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gt_x_1             | DW_cmp           | apparch (area)     |                |
| lt_x_2             | DW_cmp           | apparch (area)     |                |
| lt_x_36            | DW_cmp           | apparch (area)     |                |
| gt_x_37            | DW_cmp           | apparch (area)     |                |
| lt_x_38            | DW_cmp           | apparch (area)     |                |
| gt_x_39            | DW_cmp           | apparch (area)     |                |
| lt_x_40            | DW_cmp           | apparch (area)     |                |
| gt_x_41            | DW_cmp           | apparch (area)     |                |
| div_77             | DW_div_uns       | cla3               |                |
| div_78             | DW_div_uns       | cla2               |                |
| gt_x_79            | DW_cmp           | apparch (area)     |                |
| gt_x_81            | DW_cmp           | apparch (area)     |                |
| gt_x_83            | DW_cmp           | apparch (area)     |                |
| gt_x_85            | DW_cmp           | apparch (area)     |                |
| gt_x_87            | DW_cmp           | apparch (area)     |                |
| gt_x_89            | DW_cmp           | apparch (area)     |                |
| sub_x_99           | DW01_sub         | apparch (area)     |                |
| sub_x_100          | DW01_sub         | apparch (area)     |                |
| sub_x_101          | DW01_sub         | apparch (area)     |                |
| sub_x_102          | DW01_sub         | apparch (area)     |                |
| sub_x_103          | DW01_sub         | apparch (area)     |                |
| sub_x_104          | DW01_sub         | apparch (area)     |                |
| sub_x_105          | DW01_sub         | apparch (area)     |                |
| sub_x_106          | DW01_sub         | apparch (area)     |                |
| gt_x_113           | DW_cmp           | apparch (area)     |                |
| gt_x_114           | DW_cmp           | apparch (area)     |                |
| lt_x_115           | DW_cmp           | apparch (area)     |                |
| lt_x_116           | DW_cmp           | apparch (area)     |                |
| gt_x_117           | DW_cmp           | apparch (area)     |                |
| lt_x_118           | DW_cmp           | apparch (area)     |                |
| gt_x_119           | DW_cmp           | apparch (area)     |                |
| add_x_6            | DW01_inc         | apparch (area)     |                |
| DP_OP_293J1_122_2512                  |                    |                |
|                    | DP_OP_293J1_122_2512 | str (area)     |                |
| DP_OP_294J1_123_9307                  |                    |                |
|                    | DP_OP_294J1_123_9307 | str (area,speed)                |
|                    |                  | mult_arch: benc_radix4              |
|                    |                  | mult_arch: and     |                |
| DP_OP_295J1_124_2519                  |                    |                |
|                    | DP_OP_295J1_124_2519 | str (area,speed)                |
|                    |                  | mult_arch: and     |                |
===============================================================================

1
