 
****************************************
Report : resources
Design : SNN
Version: T-2022.03
Date   : Sat Apr 22 20:55:32 2023
****************************************


Resource Report for this hierarchy in file
        /RAID2/COURSE/iclab/iclab034/Lab08/EXERCISE/01_RTL/SNN.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gt_x_1         | DW_cmp         | width=6    | gt_170 (SNN.v:170)         |
| lt_x_2         | DW_cmp         | width=6    | lt_170 (SNN.v:170)         |
| lt_x_36        | DW_cmp         | width=6    | lt_318 (SNN.v:318)         |
| gt_x_37        | DW_cmp         | width=6    | gt_319 (SNN.v:319)         |
| lt_x_38        | DW_cmp         | width=6    | lt_319 (SNN.v:319)         |
| gt_x_39        | DW_cmp         | width=6    | gt_320 (SNN.v:320)         |
| lt_x_40        | DW_cmp         | width=6    | lt_320 (SNN.v:320)         |
| gt_x_41        | DW_cmp         | width=6    | gt_321 (SNN.v:321)         |
| div_75         | DW_div_uns     | a_width=20 | div_491 (SNN.v:491)        |
|                |                | b_width=12 |                            |
| div_76         | DW_div_uns     | a_width=17 | div_492 (SNN.v:492)        |
|                |                | b_width=9  |                            |
| gt_x_77        | DW_cmp         | width=8    | gt_497 (SNN.v:497)         |
| gt_x_79        | DW_cmp         | width=8    | gt_498 (SNN.v:498)         |
| gt_x_81        | DW_cmp         | width=8    | gt_499 (SNN.v:499)         |
| gt_x_83        | DW_cmp         | width=8    | gt_501 (SNN.v:501)         |
| gt_x_85        | DW_cmp         | width=8    | gt_502 (SNN.v:502)         |
| gt_x_87        | DW_cmp         | width=8    | gt_503 (SNN.v:503)         |
| sub_x_97       | DW01_sub       | width=9    | sub_520 (SNN.v:520)        |
| sub_x_98       | DW01_sub       | width=9    | sub_521 (SNN.v:521)        |
| sub_x_99       | DW01_sub       | width=9    | sub_522 (SNN.v:522)        |
| sub_x_100      | DW01_sub       | width=9    | sub_523 (SNN.v:523)        |
| sub_x_101      | DW01_sub       | width=8    | sub_525 (SNN.v:525)        |
| sub_x_102      | DW01_sub       | width=8    | sub_526 (SNN.v:526)        |
| sub_x_103      | DW01_sub       | width=8    | sub_527 (SNN.v:527)        |
| sub_x_104      | DW01_sub       | width=8    | sub_528 (SNN.v:528)        |
| gt_x_113       | DW_cmp         | width=6    | gt_165 (SNN.v:165)         |
|                |                |            | gt_318 (SNN.v:318)         |
|                |                |            | gt_430 (SNN.v:430)         |
|                |                |            | gt_431 (SNN.v:431)         |
|                |                |            | gt_432 (SNN.v:432)         |
|                |                |            | gt_433 (SNN.v:433)         |
|                |                |            | gt_435 (SNN.v:435)         |
|                |                |            | gt_436 (SNN.v:436)         |
|                |                |            | gt_437 (SNN.v:437)         |
|                |                |            | gt_438 (SNN.v:438)         |
|                |                |            | gt_439 (SNN.v:439)         |
|                |                |            | gt_440 (SNN.v:440)         |
|                |                |            | gt_441 (SNN.v:441)         |
|                |                |            | gt_442 (SNN.v:442)         |
|                |                |            | gt_443 (SNN.v:443)         |
|                |                |            | gt_444 (SNN.v:444)         |
|                |                |            | gt_445 (SNN.v:445)         |
|                |                |            | gt_446 (SNN.v:446)         |
|                |                |            | gt_447 (SNN.v:447)         |
|                |                |            | gt_448 (SNN.v:448)         |
| gt_x_114       | DW_cmp         | width=6    | gt_169 (SNN.v:169)         |
|                |                |            | gt_171 (SNN.v:171)         |
| lt_x_115       | DW_cmp         | width=6    | lt_169 (SNN.v:169)         |
|                |                |            | lt_171 (SNN.v:171)         |
| lt_x_116       | DW_cmp         | width=6    | lt_298_G3_G3 (SNN.v:298)   |
|                |                |            | lt_305 (SNN.v:305)         |
|                |                |            | lt_305_G2 (SNN.v:305)      |
|                |                |            | lt_305_G2_G1 (SNN.v:305)   |
|                |                |            | lt_305_G2_G2 (SNN.v:305)   |
|                |                |            | lt_305_G2_G3 (SNN.v:305)   |
|                |                |            | lt_305_G3 (SNN.v:305)      |
|                |                |            | lt_305_G3_G1 (SNN.v:305)   |
|                |                |            | lt_305_G3_G2 (SNN.v:305)   |
| lt_x_117       | DW_cmp         | width=6    | lt_482 (SNN.v:482)         |
|                |                |            | lt_483 (SNN.v:483)         |
| gt_x_118       | DW_cmp         | width=6    | gt_482 (SNN.v:482)         |
|                |                |            | gt_483 (SNN.v:483)         |
| gt_x_119       | DW_cmp         | width=3    | gt_509 (SNN.v:509)         |
|                |                |            | gt_510 (SNN.v:510)         |
|                |                |            | gt_511 (SNN.v:511)         |
|                |                |            | gt_512 (SNN.v:512)         |
|                |                |            | gt_513 (SNN.v:513)         |
|                |                |            | gt_514 (SNN.v:514)         |
|                |                |            | gt_515 (SNN.v:515)         |
|                |                |            | gt_516 (SNN.v:516)         |
| add_x_6        | DW01_inc       | width=6    | add_232 (SNN.v:232)        |
|                |                |            | add_233 (SNN.v:233)        |
|                |                |            | add_236 (SNN.v:236)        |
| DP_OP_292J1_122_2512            |            |                            |
|                | DP_OP_292J1_122_2512 |      |                            |
| DP_OP_293J1_123_8069            |            |                            |
|                | DP_OP_293J1_123_8069 |      |                            |
| DP_OP_294J1_124_2519            |            |                            |
|                | DP_OP_294J1_124_2519 |      |                            |
=============================================================================

Datapath Report for DP_OP_292J1_122_2512
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_292J1_122_2512 | add_539 (SNN.v:539) add_539_2 (SNN.v:539)           |
|                      | add_539_3 (SNN.v:539)                               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 + I4 (SNN.v:539)            |
==============================================================================

Datapath Report for DP_OP_293J1_123_8069
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_293J1_123_8069 | mult_455_G3 (SNN.v:455) add_476 (SNN.v:476)         |
|                      | add_479 (SNN.v:479) add_477 (SNN.v:477)             |
|                      | add_479_2 (SNN.v:479) add_478 (SNN.v:478)           |
|                      | add_479_3 (SNN.v:479) add_479_4 (SNN.v:479)         |
|                      | mult_455_G4 (SNN.v:455) add_475 (SNN.v:475)         |
|                      | mult_455 (SNN.v:455) mult_455_G2 (SNN.v:455)        |
|                      | mult_455_G5 (SNN.v:455) mult_455_G6 (SNN.v:455)     |
|                      | mult_455_G7 (SNN.v:455) mult_455_G8 (SNN.v:455)     |
|                      | mult_455_G9 (SNN.v:455)                             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| I5    | PI   | Unsigned | 8     |                                          |
| I6    | PI   | Unsigned | 8     |                                          |
| I7    | PI   | Unsigned | 8     |                                          |
| I8    | PI   | Unsigned | 8     |                                          |
| I9    | PI   | Unsigned | 8     |                                          |
| I10   | PI   | Unsigned | 8     |                                          |
| I11   | PI   | Unsigned | 8     |                                          |
| I12   | PI   | Unsigned | 8     |                                          |
| I13   | PI   | Unsigned | 8     |                                          |
| I14   | PI   | Unsigned | 8     |                                          |
| I15   | PI   | Unsigned | 8     |                                          |
| I16   | PI   | Unsigned | 8     |                                          |
| I17   | PI   | Unsigned | 8     |                                          |
| I18   | PI   | Unsigned | 8     |                                          |
| T108  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:455)                      |
| T109  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:455)                      |
| T106  | IFO  | Unsigned | 16    | I5 * I6 (SNN.v:455)                      |
| T107  | IFO  | Unsigned | 16    | I7 * I8 (SNN.v:455)                      |
| T110  | IFO  | Unsigned | 16    | I9 * I10 (SNN.v:455)                     |
| T111  | IFO  | Unsigned | 16    | I11 * I12 (SNN.v:455)                    |
| T112  | IFO  | Unsigned | 16    | I13 * I14 (SNN.v:455)                    |
| T113  | IFO  | Unsigned | 16    | I15 * I16 (SNN.v:455)                    |
| T114  | IFO  | Unsigned | 16    | I17 * I18 (SNN.v:455)                    |
| O1    | PO   | Unsigned | 20    | T108 + T109 + O2 + T110 + T111 + T112 + T113 + T114 ( SNN.v:476 SNN.v:477 SNN.v:478 SNN.v:479 ) |
| O2    | PO   | Unsigned | 17    | T106 + T107 (SNN.v:475)                  |
==============================================================================

Datapath Report for DP_OP_294J1_124_2519
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_294J1_124_2519 | mult_486 (SNN.v:486) add_486 (SNN.v:486)            |
|                      | mult_486_2 (SNN.v:486)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| T129  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:486)                      |
| T130  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:486)                      |
| O1    | PO   | Unsigned | 17    | T129 + T130 (SNN.v:486)                  |
==============================================================================


Resource Report for Ungrouped Hierarchy div_76
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy div_75
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'sub_525 (SNN.v:525)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3140 (SNN.v:534)'.  (HDL-120)

Information: Operator associated with resources 'sub_526 (SNN.v:526)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3141 (SNN.v:535)'.  (HDL-120)

Information: Operator associated with resources 'sub_527 (SNN.v:527)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3142 (SNN.v:536)'.  (HDL-120)

Information: Operator associated with resources 'sub_528 (SNN.v:528)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3143 (SNN.v:537)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gt_x_1             | DW_cmp           | apparch (area)     |                |
| lt_x_2             | DW_cmp           | apparch (area)     |                |
| lt_x_36            | DW_cmp           | apparch (area)     |                |
| gt_x_37            | DW_cmp           | apparch (area)     |                |
| lt_x_38            | DW_cmp           | apparch (area)     |                |
| gt_x_39            | DW_cmp           | apparch (area)     |                |
| lt_x_40            | DW_cmp           | apparch (area)     |                |
| gt_x_41            | DW_cmp           | apparch (area)     |                |
| div_75             | DW_div_uns       | cla2               |                |
| div_76             | DW_div_uns       | cla2               |                |
| gt_x_77            | DW_cmp           | apparch (area)     |                |
| gt_x_79            | DW_cmp           | apparch (area)     |                |
| gt_x_81            | DW_cmp           | apparch (area)     |                |
| gt_x_83            | DW_cmp           | apparch (area)     |                |
| gt_x_85            | DW_cmp           | apparch (area)     |                |
| gt_x_87            | DW_cmp           | apparch (area)     |                |
| sub_x_97           | DW01_sub         | apparch (area)     |                |
| sub_x_98           | DW01_sub         | apparch (area)     |                |
| sub_x_99           | DW01_sub         | apparch (area)     |                |
| sub_x_100          | DW01_sub         | apparch (area)     |                |
| sub_x_101          | DW01_sub         | apparch (area)     |                |
| sub_x_102          | DW01_sub         | apparch (area)     |                |
| sub_x_103          | DW01_sub         | apparch (area)     |                |
| sub_x_104          | DW01_sub         | apparch (area)     |                |
| gt_x_113           | DW_cmp           | apparch (area)     |                |
| gt_x_114           | DW_cmp           | apparch (area)     |                |
| lt_x_115           | DW_cmp           | apparch (area)     |                |
| lt_x_116           | DW_cmp           | apparch (area)     |                |
| lt_x_117           | DW_cmp           | apparch (area)     |                |
| gt_x_118           | DW_cmp           | apparch (area)     |                |
| gt_x_119           | DW_cmp           | apparch (area)     |                |
| add_x_6            | DW01_inc         | apparch (area)     |                |
| DP_OP_292J1_122_2512                  |                    |                |
|                    | DP_OP_292J1_122_2512 | str (area)     |                |
| DP_OP_293J1_123_8069                  |                    |                |
|                    | DP_OP_293J1_123_8069 | str (area,speed)                |
|                    |                  | mult_arch: and     |                |
|                    |                  | mult_arch: and     |                |
| DP_OP_294J1_124_2519                  |                    |                |
|                    | DP_OP_294J1_124_2519 | str (area)     |                |
|                    |                  | mult_arch: and     |                |
===============================================================================

1
