 
****************************************
Report : resources
Design : SNN
Version: T-2022.03
Date   : Sat Apr 22 11:22:14 2023
****************************************


Resource Report for this hierarchy in file
        /RAID2/COURSE/iclab/iclab034/Lab08/EXERCISE/01_RTL/SNN.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gt_x_1         | DW_cmp         | width=6    | gt_157 (SNN.v:157)         |
| lt_x_2         | DW_cmp         | width=6    | lt_157 (SNN.v:157)         |
| lt_x_36        | DW_cmp         | width=6    | lt_305 (SNN.v:305)         |
| gt_x_37        | DW_cmp         | width=6    | gt_306 (SNN.v:306)         |
| lt_x_38        | DW_cmp         | width=6    | lt_306 (SNN.v:306)         |
| gt_x_39        | DW_cmp         | width=6    | gt_307 (SNN.v:307)         |
| lt_x_40        | DW_cmp         | width=6    | lt_307 (SNN.v:307)         |
| gt_x_41        | DW_cmp         | width=6    | gt_308 (SNN.v:308)         |
| div_75         | DW_div_uns     | a_width=20 | div_476 (SNN.v:476)        |
|                |                | b_width=12 |                            |
| div_76         | DW_div_uns     | a_width=17 | div_477 (SNN.v:477)        |
|                |                | b_width=9  |                            |
| gt_x_77        | DW_cmp         | width=8    | gt_482 (SNN.v:482)         |
| gt_x_79        | DW_cmp         | width=8    | gt_483 (SNN.v:483)         |
| gt_x_81        | DW_cmp         | width=8    | gt_484 (SNN.v:484)         |
| gt_x_83        | DW_cmp         | width=8    | gt_486 (SNN.v:486)         |
| gt_x_85        | DW_cmp         | width=8    | gt_487 (SNN.v:487)         |
| gt_x_87        | DW_cmp         | width=8    | gt_488 (SNN.v:488)         |
| sub_x_97       | DW01_sub       | width=9    | sub_505 (SNN.v:505)        |
| sub_x_98       | DW01_sub       | width=9    | sub_506 (SNN.v:506)        |
| sub_x_99       | DW01_sub       | width=9    | sub_507 (SNN.v:507)        |
| sub_x_100      | DW01_sub       | width=9    | sub_508 (SNN.v:508)        |
| sub_x_101      | DW01_sub       | width=8    | sub_510 (SNN.v:510)        |
| sub_x_102      | DW01_sub       | width=8    | sub_511 (SNN.v:511)        |
| sub_x_103      | DW01_sub       | width=8    | sub_512 (SNN.v:512)        |
| sub_x_104      | DW01_sub       | width=8    | sub_513 (SNN.v:513)        |
| gt_x_113       | DW_cmp         | width=6    | gt_152 (SNN.v:152)         |
|                |                |            | gt_305 (SNN.v:305)         |
|                |                |            | gt_415 (SNN.v:415)         |
|                |                |            | gt_416 (SNN.v:416)         |
|                |                |            | gt_417 (SNN.v:417)         |
|                |                |            | gt_418 (SNN.v:418)         |
|                |                |            | gt_420 (SNN.v:420)         |
|                |                |            | gt_421 (SNN.v:421)         |
|                |                |            | gt_422 (SNN.v:422)         |
|                |                |            | gt_423 (SNN.v:423)         |
|                |                |            | gt_424 (SNN.v:424)         |
|                |                |            | gt_425 (SNN.v:425)         |
|                |                |            | gt_426 (SNN.v:426)         |
|                |                |            | gt_427 (SNN.v:427)         |
|                |                |            | gt_428 (SNN.v:428)         |
|                |                |            | gt_429 (SNN.v:429)         |
|                |                |            | gt_430 (SNN.v:430)         |
|                |                |            | gt_431 (SNN.v:431)         |
|                |                |            | gt_432 (SNN.v:432)         |
|                |                |            | gt_433 (SNN.v:433)         |
| gt_x_114       | DW_cmp         | width=6    | gt_156 (SNN.v:156)         |
|                |                |            | gt_158 (SNN.v:158)         |
| lt_x_115       | DW_cmp         | width=6    | lt_156 (SNN.v:156)         |
|                |                |            | lt_158 (SNN.v:158)         |
| lt_x_116       | DW_cmp         | width=6    | lt_285_G3_G3 (SNN.v:285)   |
|                |                |            | lt_292 (SNN.v:292)         |
|                |                |            | lt_292_G2 (SNN.v:292)      |
|                |                |            | lt_292_G2_G1 (SNN.v:292)   |
|                |                |            | lt_292_G2_G2 (SNN.v:292)   |
|                |                |            | lt_292_G2_G3 (SNN.v:292)   |
|                |                |            | lt_292_G3 (SNN.v:292)      |
|                |                |            | lt_292_G3_G1 (SNN.v:292)   |
|                |                |            | lt_292_G3_G2 (SNN.v:292)   |
| lt_x_117       | DW_cmp         | width=6    | lt_467 (SNN.v:467)         |
|                |                |            | lt_468 (SNN.v:468)         |
| gt_x_118       | DW_cmp         | width=6    | gt_467 (SNN.v:467)         |
|                |                |            | gt_468 (SNN.v:468)         |
| gt_x_119       | DW_cmp         | width=3    | gt_494 (SNN.v:494)         |
|                |                |            | gt_495 (SNN.v:495)         |
|                |                |            | gt_496 (SNN.v:496)         |
|                |                |            | gt_497 (SNN.v:497)         |
|                |                |            | gt_498 (SNN.v:498)         |
|                |                |            | gt_499 (SNN.v:499)         |
|                |                |            | gt_500 (SNN.v:500)         |
|                |                |            | gt_501 (SNN.v:501)         |
| add_x_6        | DW01_inc       | width=6    | add_219 (SNN.v:219)        |
|                |                |            | add_220 (SNN.v:220)        |
|                |                |            | add_223 (SNN.v:223)        |
| DP_OP_292J1_122_2512            |            |                            |
|                | DP_OP_292J1_122_2512 |      |                            |
| DP_OP_293J1_123_8069            |            |                            |
|                | DP_OP_293J1_123_8069 |      |                            |
| DP_OP_294J1_124_2519            |            |                            |
|                | DP_OP_294J1_124_2519 |      |                            |
=============================================================================

Datapath Report for DP_OP_292J1_122_2512
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_292J1_122_2512 | add_524 (SNN.v:524) add_524_2 (SNN.v:524)           |
|                      | add_524_3 (SNN.v:524)                               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 10    | I1 + I2 + I3 + I4 (SNN.v:524)            |
==============================================================================

Datapath Report for DP_OP_293J1_123_8069
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_293J1_123_8069 | mult_440_G3 (SNN.v:440) add_461 (SNN.v:461)         |
|                      | add_464 (SNN.v:464) add_462 (SNN.v:462)             |
|                      | add_464_2 (SNN.v:464) add_463 (SNN.v:463)           |
|                      | add_464_3 (SNN.v:464) add_464_4 (SNN.v:464)         |
|                      | mult_440_G4 (SNN.v:440) add_460 (SNN.v:460)         |
|                      | mult_440 (SNN.v:440) mult_440_G2 (SNN.v:440)        |
|                      | mult_440_G5 (SNN.v:440) mult_440_G6 (SNN.v:440)     |
|                      | mult_440_G7 (SNN.v:440) mult_440_G8 (SNN.v:440)     |
|                      | mult_440_G9 (SNN.v:440)                             |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| I5    | PI   | Unsigned | 8     |                                          |
| I6    | PI   | Unsigned | 8     |                                          |
| I7    | PI   | Unsigned | 8     |                                          |
| I8    | PI   | Unsigned | 8     |                                          |
| I9    | PI   | Unsigned | 8     |                                          |
| I10   | PI   | Unsigned | 8     |                                          |
| I11   | PI   | Unsigned | 8     |                                          |
| I12   | PI   | Unsigned | 8     |                                          |
| I13   | PI   | Unsigned | 8     |                                          |
| I14   | PI   | Unsigned | 8     |                                          |
| I15   | PI   | Unsigned | 8     |                                          |
| I16   | PI   | Unsigned | 8     |                                          |
| I17   | PI   | Unsigned | 8     |                                          |
| I18   | PI   | Unsigned | 8     |                                          |
| T108  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:440)                      |
| T109  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:440)                      |
| T106  | IFO  | Unsigned | 16    | I5 * I6 (SNN.v:440)                      |
| T107  | IFO  | Unsigned | 16    | I7 * I8 (SNN.v:440)                      |
| T110  | IFO  | Unsigned | 16    | I9 * I10 (SNN.v:440)                     |
| T111  | IFO  | Unsigned | 16    | I11 * I12 (SNN.v:440)                    |
| T112  | IFO  | Unsigned | 16    | I13 * I14 (SNN.v:440)                    |
| T113  | IFO  | Unsigned | 16    | I15 * I16 (SNN.v:440)                    |
| T114  | IFO  | Unsigned | 16    | I17 * I18 (SNN.v:440)                    |
| O1    | PO   | Unsigned | 20    | T108 + T109 + O2 + T110 + T111 + T112 + T113 + T114 ( SNN.v:461 SNN.v:462 SNN.v:463 SNN.v:464 ) |
| O2    | PO   | Unsigned | 17    | T106 + T107 (SNN.v:460)                  |
==============================================================================

Datapath Report for DP_OP_294J1_124_2519
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_294J1_124_2519 | mult_471 (SNN.v:471) add_471 (SNN.v:471)            |
|                      | mult_471_2 (SNN.v:471)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| I4    | PI   | Unsigned | 8     |                                          |
| T129  | IFO  | Unsigned | 16    | I1 * I2 (SNN.v:471)                      |
| T130  | IFO  | Unsigned | 16    | I3 * I4 (SNN.v:471)                      |
| O1    | PO   | Unsigned | 17    | T129 + T130 (SNN.v:471)                  |
==============================================================================


Resource Report for Ungrouped Hierarchy div_76
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Resource Report for Ungrouped Hierarchy div_75
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
=============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'sub_510 (SNN.v:510)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3103 (SNN.v:519)'.  (HDL-120)

Information: Operator associated with resources 'sub_511 (SNN.v:511)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3104 (SNN.v:520)'.  (HDL-120)

Information: Operator associated with resources 'sub_512 (SNN.v:512)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3105 (SNN.v:521)'.  (HDL-120)

Information: Operator associated with resources 'sub_513 (SNN.v:513)' in design 'SNN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C3106 (SNN.v:522)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gt_x_1             | DW_cmp           | apparch (area)     |                |
| lt_x_2             | DW_cmp           | apparch (area)     |                |
| lt_x_36            | DW_cmp           | apparch (area)     |                |
| gt_x_37            | DW_cmp           | apparch (area)     |                |
| lt_x_38            | DW_cmp           | apparch (area)     |                |
| gt_x_39            | DW_cmp           | apparch (area)     |                |
| lt_x_40            | DW_cmp           | apparch (area)     |                |
| gt_x_41            | DW_cmp           | apparch (area)     |                |
| div_75             | DW_div_uns       | cla2               |                |
| div_76             | DW_div_uns       | cla2               |                |
| gt_x_77            | DW_cmp           | apparch (area)     |                |
| gt_x_79            | DW_cmp           | apparch (area)     |                |
| gt_x_81            | DW_cmp           | apparch (area)     |                |
| gt_x_83            | DW_cmp           | apparch (area)     |                |
| gt_x_85            | DW_cmp           | apparch (area)     |                |
| gt_x_87            | DW_cmp           | apparch (area)     |                |
| sub_x_97           | DW01_sub         | apparch (area)     |                |
| sub_x_98           | DW01_sub         | apparch (area)     |                |
| sub_x_99           | DW01_sub         | apparch (area)     |                |
| sub_x_100          | DW01_sub         | apparch (area)     |                |
| sub_x_101          | DW01_sub         | apparch (area)     |                |
| sub_x_102          | DW01_sub         | apparch (area)     |                |
| sub_x_103          | DW01_sub         | apparch (area)     |                |
| sub_x_104          | DW01_sub         | apparch (area)     |                |
| gt_x_113           | DW_cmp           | apparch (area)     |                |
| gt_x_114           | DW_cmp           | apparch (area)     |                |
| lt_x_115           | DW_cmp           | apparch (area)     |                |
| lt_x_116           | DW_cmp           | apparch (area)     |                |
| lt_x_117           | DW_cmp           | apparch (area)     |                |
| gt_x_118           | DW_cmp           | apparch (area)     |                |
| gt_x_119           | DW_cmp           | apparch (area)     |                |
| add_x_6            | DW01_inc         | apparch (area)     |                |
| DP_OP_292J1_122_2512                  |                    |                |
|                    | DP_OP_292J1_122_2512 | str (area)     |                |
| DP_OP_293J1_123_8069                  |                    |                |
|                    | DP_OP_293J1_123_8069 | str (area,speed)                |
|                    |                  | mult_arch: and     |                |
|                    |                  | mult_arch: and     |                |
| DP_OP_294J1_124_2519                  |                    |                |
|                    | DP_OP_294J1_124_2519 | str (area)     |                |
|                    |                  | mult_arch: and     |                |
===============================================================================

1
